services:
  go:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    user: vscode
    volumes:
      - "../.:/app"
    tty: true
    init: true
    command: /bin/bash
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_URI: ${DB_URI}

  database:
    image: postgres:13.16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
